name: Waka Readme

on:
  # 每天世界标准时间 0点 (北京时间早上8点) 自动运行
  schedule:
    - cron: '0 0 * * *'
  # 允许你手动点击按钮触发更新 (方便测试)
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 下面这些是配置显示内容的，可以根据喜好调整
          SHOW_OS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          # 你的提交文案
          COMMIT_MESSAGE: "Updated waka-readme-stats"

